from building import *

cwd = GetCurrentDir()
# if use Rust driver
#src = Glob('*.c')
# if use C driver
src = Glob('*.c') + Glob('./C/*.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = ['RT_USING_LWIP'], CPPPATH = CPPPATH)

Return('group')
