from building import *

cwd = GetCurrentDir()
# if use Rust driver
#src = Glob('*.c') + Glob('*.cpp') + Glob('*_gcc.S') + Glob('*.a')
# if use C driver
src = Glob('*.c') + Glob('*.cpp') + Glob('*_gcc.S')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')
